"use client";
import {useState} from "react";

const tools=["Playwright","TypeScript","JavaScript","Python","Appium","Postman","Jira","TestRail","Xray","SQL","k6","Jenkins","GitHub Actions","Claude Code"];
const work=[
{n:"01",tag:"SHIFT-LEFT · TEST STRATEGY",en:{title:"Quality before the first line of code",copy:"Designed test plans from requirements and acceptance criteria before development began, making risks visible when they were still inexpensive to solve.",value:"90%",label:"of monthly test plans ready before development"},es:{title:"Calidad antes de la primera línea de código",copy:"Diseñé planes de prueba desde los requerimientos y criterios de aceptación antes de comenzar el desarrollo, haciendo visibles los riesgos cuando todavía era económico resolverlos.",value:"90%",label:"de los planes mensuales listos antes del desarrollo"},tone:"lime"},
{n:"02",tag:"AGENTIC QA · PLAYWRIGHT",en:{title:"An AI-assisted review workflow",copy:"Built QA agents grounded in ISTQB techniques to compare test plans against pull requests, expose missing scenarios, and keep coverage consistent and auditable.",value:"Weekly",label:"automation and agent maintenance"},es:{title:"Un flujo de revisión asistido por IA",copy:"Construí agentes de QA basados en técnicas ISTQB para comparar planes de prueba con pull requests, detectar escenarios faltantes y mantener una cobertura consistente y auditable.",value:"Semanal",label:"mantenimiento de automatización y agentes"},tone:"violet"},
{n:"03",tag:"LOGISTICS · END-TO-END QUALITY",en:{title:"Confidence for complex routing flows",copy:"Validated web, mobile, APIs, integrations and route-optimization algorithms across real operational constraints and critical business scenarios.",value:"25%",label:"of tasks tested each month returned before production"},es:{title:"Confianza para flujos logísticos complejos",copy:"Validé web, mobile, APIs, integraciones y algoritmos de optimización de rutas con restricciones operativas reales y escenarios críticos de negocio.",value:"25%",label:"de las tareas testeadas por mes volvieron antes de producción"},tone:"sand"}];

const softSkills=[
{en:{title:"Assertive communication",copy:"I make risks, blockers and decisions visible without creating friction."},es:{title:"Comunicación asertiva",copy:"Hago visibles riesgos, bloqueos y decisiones sin generar fricción."}},
{en:{title:"Critical thinking",copy:"I challenge assumptions and look for the question behind the requirement."},es:{title:"Pensamiento crítico",copy:"Cuestiono supuestos y busco la pregunta que existe detrás del requerimiento."}},
{en:{title:"Team collaboration",copy:"I work closely with Product and Development from refinement to release."},es:{title:"Colaboración",copy:"Trabajo junto a Producto y Desarrollo desde el refinamiento hasta el release."}},
{en:{title:"Adaptability",copy:"I move across teams, products and technical contexts while keeping quality consistent."},es:{title:"Adaptabilidad",copy:"Me adapto a equipos, productos y contextos técnicos manteniendo una calidad consistente."}}];

const testExamples=[
{id:"TC-LOGIN-001",type:{en:"Positive · Smoke",es:"Positivo · Smoke"},priority:"P0",title:{en:"Successful login with a standard user",es:"Inicio de sesión exitoso con usuario estándar"},pre:{en:"A valid and active standard_user exists.",es:"Existe un usuario standard_user válido y activo."},steps:{en:["Open the login page","Enter valid credentials","Select “Login”"],es:["Abrir la página de inicio","Ingresar credenciales válidas","Seleccionar “Login”"]},expected:{en:"The inventory page loads and the authenticated session is created.",es:"Se muestra el inventario y se crea la sesión autenticada."},tech:{en:"Equivalence Partitioning",es:"Partición de Equivalencia"},repo:"https://github.com/imalisani/playwright-portfolio-typescript"},
{id:"TC-LOGIN-002",type:{en:"Negative · Regression",es:"Negativo · Regresión"},priority:"P0",title:{en:"Blocked user cannot access the product",es:"Un usuario bloqueado no puede acceder al producto"},pre:{en:"The locked_out_user is blocked by the system.",es:"El usuario locked_out_user está bloqueado por el sistema."},steps:{en:["Open the login page","Enter the blocked user credentials","Select “Login”"],es:["Abrir la página de inicio","Ingresar las credenciales del usuario bloqueado","Seleccionar “Login”"]},expected:{en:"Access is denied and the exact locked-user message is displayed.",es:"Se deniega el acceso y se muestra el mensaje exacto para usuario bloqueado."},tech:{en:"Negative testing · Error oracle",es:"Testing negativo · Oráculo de error"},repo:"https://github.com/imalisani/playwright-portfolio-typescript"},
{id:"TC-A11Y-003",type:{en:"Accessibility · Known defect",es:"Accesibilidad · Defecto conocido"},priority:"P1",title:{en:"Inventory controls have accessible names",es:"Los controles del inventario tienen nombres accesibles"},pre:{en:"The user is authenticated and the inventory is visible.",es:"El usuario está autenticado y el inventario está visible."},steps:{en:["Run axe-core on the inventory page","Filter critical and serious violations","Inspect the reported controls"],es:["Ejecutar axe-core en el inventario","Filtrar violaciones críticas y serias","Inspeccionar los controles reportados"]},expected:{en:"Every interactive control exposes an accessible name. A missing name is tracked as BUG-001.",es:"Cada control interactivo expone un nombre accesible. La ausencia se registra como BUG-001."},tech:{en:"WCAG 4.1.2 · Cross-tool confirmation",es:"WCAG 4.1.2 · Confirmación cruzada"},repo:"https://github.com/imalisani/selenium-portfolio-python"}];

const repos=[
{n:"01",name:"imalisani / profile",stack:"QUALITY ENGINEERING · AGENTIC QA",url:"https://github.com/imalisani/imalisani",en:"My technical profile: shift-left practice, QA agent design, measurable impact and the roadmap behind my quality engineering work.",es:"Mi perfil técnico: práctica shift-left, diseño de agentes QA, impacto medible y el roadmap detrás de mi trabajo en quality engineering."},
{n:"02",name:"playwright-portfolio-typescript",stack:"PLAYWRIGHT · TYPESCRIPT · POM · CI",url:"https://github.com/imalisani/playwright-portfolio-typescript",en:"A cross-browser E2E suite for Sauce Demo with Gherkin test plans, Page Object Model, accessibility checks, traceability and execution evidence.",es:"Suite E2E cross-browser sobre Sauce Demo con planes en Gherkin, Page Object Model, controles de accesibilidad, trazabilidad y evidencias."},
{n:"03",name:"selenium-portfolio-python",stack:"SELENIUM · PYTHON · PYTEST · AXE",url:"https://github.com/imalisani/selenium-portfolio-python",en:"The same product tested through a second driver to compare architecture, explicit waits and independently confirm accessibility findings.",es:"El mismo producto probado con un segundo driver para comparar arquitectura, esperas explícitas y confirmar hallazgos de accesibilidad."}];

const copy={
en:{nav:["Work","Test cases","GitHub","About","Contact"],available:"Available for work",location:"Argentina · Remote",hero:<>I question the<br/>product <em>before</em><br/>the user has to.</>,heroCopy:"Shift-left testing, thoughtful automation and AI-powered quality practices for products that need to move fast without losing confidence.",philosophy:"01 — Philosophy",quote:<>“The developer builds the answer.<br/>I make sure we asked the <em>right question.</em>”</>,workLabel:"02 — Selected work",workTitle:"Quality in practice.",workIntro:"Selected ways I turn ambiguity, technical complexity and product risk into reliable releases.",testsLabel:"03 — Test design samples",testsTitle:"How I think through a test.",testsIntro:"A test case is valuable when it makes the risk, data and expected behavior explicit. These examples come from my public automation suites.",pre:"Precondition",steps:"Steps",expected:"Expected result",technique:"Technique",code:"View implementation",githubLabel:"04 — Open work",githubTitle:"The thinking behind the code.",githubIntro:"Public repositories with test strategy, architecture decisions, automation and real execution evidence.",repo:"Explore repository",softLabel:"05 — Human skills",softTitle:"How I contribute to the team.",softIntro:"Quality also depends on how we communicate, collaborate and make decisions.",aboutLabel:"06 — About",aboutTitle:<>Quality is<br/>a team sport.</>,lead:"I’m Irina, a QA Engineer with almost five years of experience helping product teams prevent problems—not only find them.",about1:"At SimpliRoute, I worked across web, mobile, APIs and integrations in a complex logistics platform. My strongest work happens early: refining requirements with Product and Development, challenging assumptions, mapping risks and designing test coverage before implementation.",about2:"Today, I combine that collaborative approach with Playwright, Appium and AI agents grounded in testing fundamentals. The goal stays the same: clearer decisions, stronger releases and less friction for the team.",linkedin:"Connect on LinkedIn",cvLabel:"Open to new opportunities",cvTitle:"Want the complete picture?",cvCopy:"Download my CV for a concise overview of my experience, technical stack, education and measurable impact.",cvButton:"Download CV · PDF",toolbox:"07 — Toolbox",talk:"08 — Let’s talk",footer:<>Building something<br/>that needs <em>confidence?</em></>,contact:"Let’s work together"},
es:{nav:["Experiencia","Casos de prueba","GitHub","Sobre mí","Contacto"],available:"Disponible para trabajar",location:"Argentina · Remoto",hero:<>Cuestiono el<br/>producto <em>antes</em><br/>de que lo haga el usuario.</>,heroCopy:"Shift-left testing, automatización con criterio y prácticas de calidad potenciadas por IA para productos que necesitan avanzar rápido sin perder confianza.",philosophy:"01 — Filosofía",quote:<>“El developer construye la respuesta.<br/>Yo verifico que hayamos hecho la <em>pregunta correcta.</em>”</>,workLabel:"02 — Experiencia destacada",workTitle:"Calidad en práctica.",workIntro:"Formas concretas en las que convierto ambigüedad, complejidad técnica y riesgos de producto en releases confiables.",testsLabel:"03 — Ejemplos de diseño",testsTitle:"Cómo pienso una prueba.",testsIntro:"Un caso de prueba aporta valor cuando hace explícitos el riesgo, los datos y el comportamiento esperado. Estos ejemplos provienen de mis suites públicas.",pre:"Precondición",steps:"Pasos",expected:"Resultado esperado",technique:"Técnica",code:"Ver implementación",githubLabel:"04 — Trabajo abierto",githubTitle:"El razonamiento detrás del código.",githubIntro:"Repositorios públicos con estrategia de pruebas, decisiones de arquitectura, automatización y evidencia real de ejecución.",repo:"Explorar repositorio",softLabel:"05 — Habilidades humanas",softTitle:"Cómo aporto al equipo.",softIntro:"La calidad también depende de cómo nos comunicamos, colaboramos y tomamos decisiones.",aboutLabel:"06 — Sobre mí",aboutTitle:<>La calidad es<br/>un trabajo en equipo.</>,lead:"Soy Irina, QA Engineer con casi cinco años de experiencia ayudando a equipos de producto a prevenir problemas, no solo a encontrarlos.",about1:"En SimpliRoute trabajé sobre web, mobile, APIs e integraciones en una plataforma logística compleja. Mi mejor trabajo comienza temprano: refinando requerimientos con Producto y Desarrollo, cuestionando supuestos, mapeando riesgos y diseñando cobertura antes de implementar.",about2:"Hoy combino ese enfoque colaborativo con Playwright, Appium y agentes de IA basados en fundamentos de testing. El objetivo sigue siendo el mismo: decisiones más claras, releases más sólidos y menos fricción para el equipo.",linkedin:"Conectar en LinkedIn",cvLabel:"Abierta a nuevas oportunidades",cvTitle:"¿Querés conocer el recorrido completo?",cvCopy:"Descargá mi CV para ver en detalle mi experiencia, stack técnico, formación e impacto medible.",cvButton:"Descargar CV · PDF",toolbox:"07 — Herramientas",talk:"08 — Hablemos",footer:<>¿Estás construyendo algo<br/>que necesita <em>confianza?</em></>,contact:"Trabajemos juntos"}};

const Arrow=()=> <span aria-hidden="true">↗</span>;
export default function Home(){
const [lang,setLang]=useState<"en"|"es">("es");
const base=copy[lang];
const c={...base,hero:lang==="es"?<>Cuestiono el<br/>producto <em>antes</em><br/>de que llegue<br/>al usuario.</>:base.hero};
return <main lang={lang}>
<nav className="nav"><a className="logo" href="#top">IM<span>.</span></a><div className="navlinks"><a href="#work">{c.nav[0]}</a><a href="#test-cases">{c.nav[1]}</a><a href="#github">{c.nav[2]}</a><a href="#about">{c.nav[3]}</a></div><div className="navActions"><button className="langSwitch" onClick={()=>setLang(lang==="en"?"es":"en")} aria-label={lang==="en"?"Ver en español":"View in English"}><span className={lang==="en"?"active":""}>EN</span><i/><span className={lang==="es"?"active":""}>ES</span></button><a className="status" href="#contact"><i/> {c.available}</a></div></nav>
<section className="hero" id="top"><div className="kicker"><span>QA Engineer</span><span>{c.location}</span></div><h1>{c.hero}</h1><div className="herofoot"><p>{c.heroCopy}</p><a className="round" href="#work">↓</a></div><div className="qaUniverse" aria-label={lang==="es"?"Universo de herramientas y conceptos QA":"QA tools and concepts universe"}><div className="orbit orbitOne"><span>{lang==="es"?"ESTRATEGIA":"SHIFT-LEFT"}</span><span>ISTQB</span><span>{lang==="es"?"RIESGOS":"RISK"}</span></div><div className="orbit orbitTwo"><span>PLAYWRIGHT</span><span>APIs</span><span>{lang==="es"?"QA CON IA":"AGENTIC QA"}</span></div><img className="planet" src="/qa-planet.png" alt={lang==="es"?"Planeta conceptual de ingeniería de calidad":"Conceptual Quality Engineering planet"}/></div></section>
<section className="statement"><p className="label">{c.philosophy}</p><blockquote>{c.quote}</blockquote></section>
<section className="work" id="work"><header className="head"><div><p className="label">{c.workLabel}</p><h2>{c.workTitle}</h2></div><p>{c.workIntro}</p></header><div className="cases">{work.map(x=>{const y=x[lang];return <article className={`case ${x.tone}`} key={x.n}><div className="casetop"><span>{x.n}</span><span>{x.tag}</span></div><div className="casebody"><h3>{y.title}</h3><p>{y.copy}</p></div><div className="impact"><strong>{y.value}</strong><span>{y.label}</span></div></article>})}</div></section>
<section className="testSection" id="test-cases"><header className="head"><div><p className="label">{c.testsLabel}</p><h2>{c.testsTitle}</h2></div><p>{c.testsIntro}</p></header><div className="testList">{testExamples.map((t,i)=><details className="testCard" key={t.id} open={i===0}><summary><span className="testId">{t.id}</span><div><small>{t.type[lang]} · {t.priority}</small><h3>{t.title[lang]}</h3></div><b aria-hidden="true">+</b></summary><div className="testDetail"><div><span>{c.pre}</span><p>{t.pre[lang]}</p></div><div><span>{c.steps}</span><ol>{t.steps[lang].map(s=><li key={s}>{s}</li>)}</ol></div><div><span>{c.expected}</span><p>{t.expected[lang]}</p></div><div><span>{c.technique}</span><p>{t.tech[lang]}</p></div><a href={t.repo} target="_blank" rel="noreferrer">{c.code} <Arrow/></a></div></details>)}</div></section>
<section className="github" id="github"><header className="head"><div><p className="label">{c.githubLabel}</p><h2>{c.githubTitle}</h2></div><p>{c.githubIntro}</p></header><div className="repoGrid">{repos.map(r=><a className="repoCard" href={r.url} target="_blank" rel="noreferrer" key={r.name}><div><span>{r.n}</span><Arrow/></div><small>{r.stack}</small><h3>{r.name}</h3><p>{r[lang]}</p><b>{c.repo} ↗</b></a>)}</div></section>
<section className="softSection"><header className="head"><div><p className="label">{c.softLabel}</p><h2>{c.softTitle}</h2></div><p>{c.softIntro}</p></header><div className="softGrid">{softSkills.map((s,i)=><article key={s.en.title}><span>0{i+1}</span><h3>{s[lang].title}</h3><p>{s[lang].copy}</p></article>)}</div></section>
<section className="about" id="about"><div><p className="label">{c.aboutLabel}</p><h2>{c.aboutTitle}</h2></div><div className="aboutcopy"><p className="lead">{c.lead}</p><p>{c.about1}</p><p>{c.about2}</p><a className="textlink" href="https://www.linkedin.com/in/imalisani/" target="_blank" rel="noreferrer">{c.linkedin} <Arrow/></a></div></section>
<section className="cvBanner"><div><p className="label">{c.cvLabel}</p><h2>{c.cvTitle}</h2><p>{c.cvCopy}</p></div><a href="/CV-Irina-Malisani-QA-Engineer.pdf" download="CV-Irina-Malisani-QA-Engineer.pdf">{c.cvButton} <span aria-hidden="true">↓</span></a></section>
<section className="toolbox"><p className="label">{c.toolbox}</p><div className="marquee"><div>{[...tools,...tools].map((t,i)=><span key={i}>{t}<b>✦</b></span>)}</div></div></section>
<footer id="contact"><p className="label">{c.talk}</p><h2>{c.footer}</h2><div className="footerbottom"><a className="contact" href="mailto:irumalisani@gmail.com">{c.contact} <Arrow/></a><div><a href="https://github.com/imalisani" target="_blank" rel="noreferrer">GitHub <Arrow/></a><a href="https://www.linkedin.com/in/imalisani/" target="_blank" rel="noreferrer">LinkedIn <Arrow/></a><span>Argentina · GMT-3</span></div></div><p className="signature">IRINA MALISANI</p></footer>
</main>}
